project:
  type: book

book:
  title: "Migration, Urbanicity, and Health: A Comprehensive Study of Mutually Reinforcing Contextual and Compositional Place-Based Determinants of Health"
  author: "Hannah Olson-Williams"
  chapters:
    - text: "Front matter"
      file: index.qmd
    - "intro.qmd"
    - "aim1.qmd"
    - "aim1_table1.qmd"
    - "aim1_table2.qmd"
    - "aim1_table3.qmd"
    - "aim1_table4.qmd"
    - "aim1_table5.qmd"
    - "aim1_table6.qmd"
    - "aim1_table7.qmd"
    - "aim1_table8.qmd"
    - "aim2.qmd"
    - "aim3.qmd"
    - "conclusion.qmd"
    - "refs.qmd"
  sidebar:
    style: "docked"

bibliography: references.bib
csl: american-statistical-association.csl
degreetype: Doctor of Philosophy
submitted: 2024
affiliation: Department of Population Health
#degrees: 'B.S. Mathematics, Case Western Reserve University'

format:
  monashthesis-html: default
  monashthesis-pdf: default
