project:
  type: book

book:
  title: "Migration, Urbanicity, and Health: Mutually Reinforcing Contextual and Compositional Place-Based Determinants of Health"
  author: "Hannah Olson-Williams"
  chapters:
    - text: "Front matter"
      file: index.qmd
    - "intro.qmd"
    - "aim1.qmd"
    - "aim2.qmd"
    - "aim3.qmd"
    - "conclusion.qmd"
    - "refs.qmd"
  appendices:
    - "appendixA.qmd"
    - "appendixB.qmd"
  sidebar:
    style: "docked"

bibliography: references.bib
csl: american-statistical-association.csl
degreetype: Doctor of Philosophy
submitted: 2024
affiliation: Department of Population Health
#degrees: 'B.S. Mathematics, Case Western Reserve University'

format:
  pdf:
    documentclass: report
    pdf-engine: xelatex
    header-includes:
      - \usepackage{setspace}
      - \doublespacing
  #monashthesis-html: default
  #monashthesis-pdf: default
  #monashthesis-docx: default
prefer-html: true
